### ISSUE TITLE
Waiting for authorization... message...

### ISSUE THREAD

**Issue by gjelsoe** [eclair4151/AlexaControlledSamsungTV#1]
It seems like some TVs needs a ID number to be send or it will ask for authorization every time.

**Comment by eclair4151** [comment]
what model is your TV?

**Comment by gjelsoe** [comment]
It's a older UE46D8000, it doen't show up on the scan list but it works.

**Comment by gaussey** [comment]
Also having the same issue, model is MU6400 and happens everytime the TV is turned off/on.

The issue is addressed here https://github.com/Ape/samsungctl/issues/48 and as mentioned involves passing the ID to avoid having to give permissions again, otherwise this works perfectly.

**Comment by eclair4151** [comment]
thanks for figuring out what was causing this. i have fixed it in 3d174c8
