### ISSUE TITLE
TV requires authorization for every request

### ISSUE THREAD

**Issue by Dennis-DZ** [eclair4151/AlexaControlledSamsungTV#12]
Every time Alexa sends a request to the TV through samsungctl, the command line shows "WARNING:root:Waiting for authorization..." and the TV shows a message asking to approve of the connection with samsungctl. This lasts for about one second and then the command line displays "Failed to send message to TV: timed out". If I quickly press enter on the TV remote to allow the connection, then the command works, but this ruins the point of the skill, which is of course to not have to use the remote. The Allshare settings say that connections with samsungctl are allowed but it still asks for every request. What can I do to make it permanently allow the connection so that the skill will work properly?

**Comment by eclair4151** [comment]
What tv model do you have? you shouldn't need to authorize it multiple times.

**Comment by Dennis-DZ** [comment]
The scan shows that the model number is UN46ES8000.

**Comment by eclair4151** [comment]
Hmm im not sure. I just use the https://github.com/Ape/samsungctl library. I would say try and use the library by hand to see if it works on the TV. if not raise an issue on there as they may be more help
