### ISSUE TITLE
Can't login to alexasmartcli.py

### ISSUE THREAD

**Issue by russellhearn69** [eclair4151/AlexaControlledSamsungTV#14]
Every time i run "python3 alexasmartcli.py login" i get this error message

Password:
Traceback (most recent call last):
File "alexasmartcli.py", line 49, in <module>
file = open('.auth/token','w')
PermissionError: [Errno 13] Permission denied: '.auth/token'

I'm not sure what to do, if anyone can help, it would be great.
Thanks

**Comment by eclair4151** [comment]
Make sure you have write permission to the directory it is located in

Thanks
Tomer

________________________________

**Comment by russellhearn69** [comment]
that solved it mate thank you, i'm new to linux so learning all the time, Thanks again
