### ISSUE TITLE
Time Out

### ISSUE THREAD

**Issue by g10chy** [eclair4151/AlexaControlledSamsungTV#15]
I have your latest version using SSL websocket but getting the following error.
Any ideas?

```
Received a new message:
b'{"volumeSteps": -10, "operation": "AdjustVolume", "endpointid": "40:16:3b:42:e1:7f"}'
from topic:
speaker/4e5a0f98-b8fc-4494-95c4-fa96a51e0e91
--------------
Failed to send message to TV: timed out
```

**Comment by eclair4151** [comment]
Hmm. can you turn on your tv and then go to 
http://(YOUR_TV_IP_ADDRESS):8001/api/v2/

and then paste the output here.
also please paste your tvconfig file contents :)

**Comment by g10chy** [comment]
Sure 

`{
  "id": "uuid:83884c64-768b-493b-9c93-342ffb2ddfca",
  "name": "[TV] Samsung 8 Series (55)",
  "version": "2.1.0",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:83884c64-768b-493b-9c93-342ffb2ddfca",
    "model": "16_JAZZM_UHD",
    "modelName": "UE55KS8000",
    "description": "Samsung DTV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.1.15",
    "firmwareVersion": "Unknown",
    "name": "[TV] Samsung 8 Series (55)",
    "id": "uuid:83884c64-768b-493b-9c93-342ffb2ddfca",
    "udn": "uuid:83884c64-768b-493b-9c93-342ffb2ddfca",
    "resolution": "3840x2160",
    "countryCode": "GB",
    "msfVersion": "2.1.0",
    "smartHubAgreement": "true",
    "VoiceSupport": "true",
    "GamePadSupport": "true",
    "wifiMac": "40:16:3b:42:e1:7f",
    "developerMode": "0",
    "developerIP": "",
    "OS": "Tizen"
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.1.15:8001/api/v2/",
  "remote": "1.0",
  "isSupport": "{\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\",\"DMP_available\":\"true\",\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"EDEN_available\":\"true\"}"
}`


tvconfig.py:
`device_name = "Home Raspberry PI" #What shows up under devices in alexasmarttv.tk. not that important unless you have multiple devices (not tvs) on your account
volume_step_size = 10  #how much your tv volume should go up by when you say 'Alexa, turn up the volume on my tv'


tvs = [
    {
        'host': "192.168.1.15", #ip address of tv
        'tv_model' : 'UE55KS8000',
        'tv_mac_address': "40:16:3b:42:e1:7f",
        'tv_name' : 'Living Room TV', #Leave as TV to refrence this by just 'TV'. ex: 'Alexa, turn on the TV'.  Change to eg:'Kitchen TV' if you want to say 'Alexa turn on the kitchen TV', You cannot have multiple tvs have the same name
        'prefer_HD': True, #if you say 'change the channel to ESPN',  always attempt to use the HD channel number'
    }
]`

**Comment by eclair4151** [comment]
hmm odd. it looks like your tv doesn't support the ssl websockets anyway. but the app should detect that and try on the correct port. 
can you try this. 

if you havent already pip install samsungctl 
https://github.com/Ape/samsungctl


and try running this python file and let me know what happens

```
import samsungctl

config =  {
    "name": "samsungctl",
    "description": "PC",
    "id": "11",
    "host": "192.168.1.15",
    "port": 8001,
    "method": "websocket",
    "timeout": 5
}

with samsungctl.Remote(config) as remote:
    remote.control("KEY_VOLDOWN")

```

**Comment by g10chy** [comment]
Get this error:

websocket._exceptions.WebSocketTimeoutException: timed out

or 

samsungctl.exceptions.UnhandledResponse: {'event': 'ms.channel.unauthorized'}

**Comment by g10chy** [comment]
Solved this now.
Thanks for your speedy responses.

Any chance you are looking to implement similar for Google Assistant?

**Comment by eclair4151** [comment]
How were you able to solve it? and i have no plans currently but who knows what the future holds :p

**Comment by g10chy** [comment]
Local firewall issue on my MacBook. 
Fingers crossed the future is bright :p
