### ISSUE TITLE
UK skill?

### ISSUE THREAD

**Issue by SeanLemon99** [eclair4151/AlexaControlledSamsungTV#2]
Is there/or could there be a UK skill for this?

**Comment by gjelsoe** [comment]
This can be used : https://www.amazon.com/dp/B07886XNK8

Just enter any US zipcode when it asks for it.

**Comment by SeanLemon99** [comment]
Thanks but that’s a US skill (at Amazon.com)

I would need to sign up for a US Amazon account, and all my Alexas are registered to my amazon.co.uk account.  So I’d have to lose all my UK skills to switch accounts.

**Comment by eclair4151** [comment]
Im working on it. UK skills require you to setup a new lambda server thats in the UK, so i cant enabled it until i set that up. hopefully soon

**Comment by eclair4151** [comment]
@SeanLemon99 the UK skill is done! i just need some help to test it. i only need some help testing with device discovery. you don't even need to have this app setup i have an account ready i just need someone to beta test the app and make sure it links properly.

**Comment by SeanLemon99** [comment]
Brill – send me the account details and I’ll give it a go!

Thanks so much for doing it!

________________________________

**Comment by eclair4151** [comment]
can you send me your email linked to your alexa account? ill send you beta access and account info on there

**Comment by eclair4151** [comment]
App has been updated for UK, Australia, India, and Canada and is live on the store
