### ISSUE TITLE
https://alexasmarttv.tk 

### ISSUE THREAD

**Issue by ilwolfeman** [eclair4151/AlexaControlledSamsungTV#22]
The website shoots back error 500 when trying to sign up for a new account. every time I try to go to the website all I can get is error 500. Any way to contact the host?

**Comment by eclair4151** [comment]
Oof that’s not good. Looking into it now!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eclair4151** [comment]
Back up and running
