### ISSUE TITLE
ERROR: Failed to send message to TV

### ISSUE THREAD

**Issue by francescoperta** [eclair4151/AlexaControlledSamsungTV#24]
Hello,
First of all great job with this development. Unfortunately, I receive the error: Failed to send message to TV.

Below is the log:

```
Received a new message: 
b'{"operation": "TurnOn", "endpointid": "50:56:BF:7E:EA:16"}'
from topic: 
power/83b13407-d7bc-4a77-8c9f-50020026644c
--------------
Failed to send message to TV:_
```

Below is the command python3 alexasmartcli.py scan
```
Scanning for TVs. make sure they are turned on and on the same network
This TV is not currently supported


Name: [TV]Samsung LED65
Model: UA65HU8500
Series: H
Ip: 192.168.1.153
MacAddress: 
```

I look forward to receiving your feedback.

Regards,

Francesco

**Comment by eclair4151** [comment]
Hey, as the message suggests your TV is not supported by my program :(

Someone made a fork of this to support H series tvs, so i would suggest you check that out, but i can't verify that it works, but worth a shot

https://github.com/bencarlisle15/AlexaControlledSamsungTV
