### ISSUE TITLE
alexasmarttv.tk is down?

### ISSUE THREAD

**Issue by Michael1947** [eclair4151/AlexaControlledSamsungTV#25]
I was able to create an account a few days back but now the website is not working. I get either a blank page or it forwards to what looks like a malware site.

**Comment by Michael1947** [comment]
This is the problem with code that relies on the cloud to work - what happens when the cloud is no longer there?  The website that runs this code: alexasmarttv.tk is apparently no longer under the control of the code author. Domaintools shows the site as “for sale”. I was very interested in controlling my Samsung TV with this but it appears that will no longer be possible. IOT will never be viable when the cloud becomes unreliable, or worse, actively hostile.

**Comment by eclair4151** [comment]
Oof thats embarsing. I had registered it as a .TK through a provider because it was free but totally forgot and it expired :( and now someone else purchased it and i would have to pay more to get it back. I have ended up purchasing alexasmarttv.dev and i am currently working on setting up the skill and ssl certificates to get it up and running. Sorry about that. i will update you when its ready to go

**Comment by Michael1947** [comment]
Thanks for the feedback.

via phone

**Comment by eclair4151** [comment]
Everything has been updated. Currently just waiting for the Alexa skill team to review the update and ship the update to the skill to authenticate against the new domain. Should hopefully be approved something in the next few days.

**Comment by eclair4151** [comment]
Welp. went to update the skill, and the entire thing got denied for having samsung and alexa in the title and url. Now my only options are buy a new domain and rebrand the entire service or take it down. lovely. Updates to come later

**Comment by itwasntme187** [comment]
any update to this? 
Went through the pain staking process of adding it to my mac mini only to find it doesn't link to the alexa app. 
thanks in advance

**Comment by eclair4151** [comment]
Sorry for the extended down time. I have registered a new subdomain for my personal site for account linking and rebranded on the Alexa store a bit. Just resubmitted for certification. I should hear back in a day or 2.

**Comment by eclair4151** [comment]
Skill was approved and everything should be back up and running. Let me know if you have any issues

**Comment by Michael1947** [comment]
It’s working! Well, mostly. I have an R series and the TV won’t turn on by voice command, but the other commands I tried seem to work pretty well. 

via phone

**Comment by sachinkudva** [comment]
Awesome, good to be back up again! Thanks!!
