### ISSUE TITLE
commands not working on Samsung 65"

### ISSUE THREAD

**Issue by smoothbond** [eclair4151/AlexaControlledSamsungTV#27]
Install went smoothly without a glitch. Commands either don't work or they work 1 out of 10 times. no error messages on the raspberry pi, commands are all being relayed properly see below. TV Model from scan is Name: [TV] Samsung 8 Series (65)
Model: UE65KS8000
Series: K
Ip: 192.168.0.37

please help. love your work

Received a new message: 
b'{"operation": "TurnOn", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
power/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "TurnOff", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
power/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "TurnOff", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
power/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Play", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Play", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Play", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Play", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Pause", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Pause", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Pause", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Pause", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Pause", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Pause", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "Pause", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
playback/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "TurnOff", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
power/6871689b-7b99-411a-a871-f97c9c434d25
--------------

Received a new message: 
b'{"operation": "TurnOff", "endpointid": "e4:7d:bd:96:b8:9b"}'
from topic: 
power/6871689b-7b99-411a-a871-f97c9c434d25

**Comment by eclair4151** [comment]
Hmm when you say 1/10 commands work, is it always the same command, or do that all only work 1/10. Its hard for me to debug things like this when i dont have access to more logs or a tv to reproduce. Give me a few days, i might try to add a debug command to the command line tool to manually trigger tv commands over LAN for better debugging

**Comment by smoothbond** [comment]
its not the same commands, I can say Alexa turn on the TV, that works most consistently, i would say 3 out of 5 times. Alexa turn off the TV hardly ever works, maybe 2 out of 10 times. alexa Pause the TV, has never worked. Alexa play TV has worked once ever.   so I went to the back of the TV to get the exact model and changed it in the config file this morning to  UE65KS8000T from UE65KS8000. But it hasn't really made a difference. As always every time i issue a command i see the output on my Pi , not a single error  . Really Weird. And I've disabled and re-enabled the skill, re-registered my pi as well.

**Comment by ajnozari** [comment]
I’m also having the same issue and it’s new for me as well.  This was working until recently.

Same logs and everything just the MU8000 series 65”

**Comment by DOA1991** [comment]
I'm also having the same issue here with the below tv

Model: UE40KU6400
Series: K

Logs similar to smoothbond


Received a new message:
b'{"operation": "TurnOff", "endpointid": "5c:49:7d:eb:e2:a8"}'
from topic:
power/0c00d4d7-2035-4e82-b90a-e2fd293a2d9f
--------------


Received a new message:
b'{"operation": "TurnOff", "endpointid": "5c:49:7d:eb:e2:a8"}'
from topic:
power/0c00d4d7-2035-4e82-b90a-e2fd293a2d9f
--------------


Received a new message:
b'{"operation": "TurnOff", "endpointid": "5c:49:7d:eb:e2:a8"}'
from topic:
power/0c00d4d7-2035-4e82-b90a-e2fd293a2d9f
--------------


Received a new message:
b'{"operation": "TurnOff", "endpointid": "5c:49:7d:eb:e2:a8"}'
from topic:
power/0c00d4d7-2035-4e82-b90a-e2fd293a2d9f
--------------


Received a new message:
b'{"operation": "TurnOff", "endpointid": "5c:49:7d:eb:e2:a8"}'
from topic:
power/0c00d4d7-2035-4e82-b90a-e2fd293a2d9f
--------------


Received a new message:
b'{"operation": "TurnOff", "endpointid": "5c:49:7d:eb:e2:a8"}'
from topic:
power/0c00d4d7-2035-4e82-b90a-e2fd293a2d9f
--------------

**Comment by eclair4151** [comment]
Have either of you seen this recently? My suspicion is this was due to a temporary AWS IoT outage.
