### ISSUE TITLE
Scan Tv for UN50NU6900 

### ISSUE THREAD

**Issue by hussen2003** [eclair4151/AlexaControlledSamsungTV#28]
The (python3 alexasmartcli.py scan) command says there are no TVs found. However the TV is connected to the same network as my laptop and echo. I would like to know if the TV model is unsupported or else. 
I am using a Chromebook with a Linux terminal if that matters.

**Comment by eclair4151** [comment]
Sorry for the delay. The scan command uses bonjour. This can fail for many reasons (firewall, port blocking, multiple routers) in any case you can get the ip, mac address, and tv version manually from the tv settings menu, and put it in the config file, and it should still work.
