### ISSUE TITLE
TV Issue get the following error

### ISSUE THREAD

**Issue by barne77** [eclair4151/AlexaControlledSamsungTV#30]
Received a new message:
b'{"operation": "TurnOn", "endpointid": "fc:8f:90:02:c3:2c"}'
from topic:
power/9a004443-75f3-453f-9553-66820b8ba2ea
--------------
Failed to send message to TV:

TV MODEL UE55JU6500

Also Scan doesnt show Mac Address

**Comment by eclair4151** [comment]
Hey, this is a J series which is unsupported. Sorry for the late response. i see you found the fork of this lib that adds expermiental support
