### ISSUE TITLE
https://alexasmarttv.dev/login - Unavailable

### ISSUE THREAD

**Issue by JO3YPz** [eclair4151/AlexaControlledSamsungTV#32]
I'm not sure whether you are still maintaining https://alexasmarttv.dev/login but there is an error on the login;

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by eclair4151** [comment]
Thank you for pointing this out. I have fixed the error, let me know if you see any other issues

**Comment by JO3YPz** [comment]
Thanks!


________________________________
