### ISSUE TITLE
H and J series support

### ISSUE THREAD

**Issue by knobtviker** [eclair4151/AlexaControlledSamsungTV#9]
As a fellow developer I'm asking what the issue is with J series?
As a user, great work, not so difficult to setup. I wish it worked with J series. 

Any progress on this subject?

**Comment by eclair4151** [comment]
Yea i never really got around to making an official way to do this. There is a slight workaround for now but i haven't been able to test as i dont have a H or J series TV, and i didn't want to push untested code.  If you want to give it a try let me know. 

my script relies on samsungctl. i have my own fork that adds support for the J series. 
https://github.com/eclair4151/samsungctl

if you want you can try setting up my fork, as per the description. Then inside this library point all instance of samsungctl to my forked version. 

Then inside https://github.com/eclair4151/AlexaControlledSamsungTV/blob/master/helpers/mqtt_server.py
modify 
def get_config(tv_mac_address):
    and
def power_off_command(tv_mac_address):

to return the correct config for your TV. 

its pretty cumbersome for now, so sorry about that

**Comment by knobtviker** [comment]
Not a problem, I followed your instruction properly.
Injected your samsungctl fork. Neat work.
Got the TV recognized and got all data about it.
Installed your skill on my Echo.
Login, register, and start server...

And on every command I get ERROR: 12602.
When using samsungctl directly, I get the same error on executing commands.
Alexa sends out a command, but the TV refuses it and returns an error 12602.

Any suggestions?

I did modify get_config to reflect a JSON with session_key and session_id, port 8000, method = "pin".

I also had to modify 
[https://github.com/eclair4151/AlexaControlledSamsungTV/blob/master/helpers/ssdp.py](https://github.com/eclair4151/AlexaControlledSamsungTV/blob/master/helpers/ssdp.py)

to remove an if else about J series. Left alone the H since I can't test either.

**Comment by eclair4151** [comment]
Hmm what is your tv model? it might be an unsupported model

**Comment by knobtviker** [comment]
Scan returns name, model, IP, and MAC. All properly filled and correct, I checked.
Model is UE48JU6400, hence the J series.

**Comment by agerdin** [comment]
Hi eclair4151, any chance that you could write me some more detailed "dummy" instructions on how to install this variant for the J-series. The instruction I do not quite follow is this:

> if you want you can try setting up my fork, as per the description. Then inside this library point all instance of samsungctl to my forked version.
> 
> Then inside https://github.com/eclair4151/AlexaControlledSamsungTV/blob/master/helpers/mqtt_server.py
> modify
> def get_config(tv_mac_address):
> and
> def power_off_command(tv_mac_address):

Any advice is appreciated.

\\Anders

**Comment by eclair4151** [comment]
I have not tested or really looked at this that much but someone is working on bringing H and J series support to this repo:

https://github.com/bencarlisle15/AlexaControlledSamsungTV

**Comment by bencarlisle15** [comment]
If anyone is still trying to find a way to connect an H or J Series, they can look at the repository I made by cloning this one and adding https://github.com/eclair4151/SmartCrypto to it. It works on my TV but there's definitely room for improvement. The fork is located at https://github.com/bencarlisle15/AlexaControlledSamsungTV/.
